name: workflow-bice

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  # 👇 Ejecución manual flexible
  workflow_dispatch:

    inputs:

      tags_expression:
        description: 'Karate tags expression'
        required: true
        default: '@smoke and not @perf'

      run_performance:
        description: 'Run performance tests'
        required: true
        default: 'false'

      suite_name:
        description: 'Suite name'
        required: true
        default: 'accounts'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  # =========================================================
  # FUNCTIONAL TESTS
  # =========================================================

  functional-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      # =====================================================
      # Push / PR → Smoke default
      # =====================================================

      - name: Run functional tests (default)
        if: github.event_name != 'workflow_dispatch'
        run: ./gradlew apiTest -Ptags="@regresion" --info

      # =====================================================
      # Manual → Dynamic tags
      # =====================================================


      - name: Run functional tests (manual)
        if: github.event_name == 'workflow_dispatch'
        run: ./gradlew apiTest -Ptags="${{ github.event.inputs.tags_expression }}" --info

      # =====================================================
      # Upload Karate Reports
      # =====================================================

      - name: Upload Karate Reports
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: build/karate-reports

  # =========================================================
  # PERFORMANCE TESTS
  # =========================================================

  performance-tests:

    needs: functional-tests

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      # =====================================================
      # Run performance only manually
      # =====================================================

      - name: Run performance tests
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_performance == 'true'
        run: ./gradlew performanceTest -Ptags=@perf

      # =====================================================
      # Prepare Gatling Site
      # =====================================================

      - name: Prepare Gatling Site
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_performance == 'true'
        run: |

          mkdir -p build/gatling-site

          latest=$(ls -td build/reports/gatling/* | head -1)

          cp -r "$latest"/* build/gatling-site/

      # =====================================================
      # Upload Gatling Reports
      # =====================================================

      - name: Upload Gatling Reports
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_performance == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: gatling-report
          path: build/gatling-site

      # =====================================================
      # Skip message
      # =====================================================

      - name: Skip performance tests
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_performance != 'true'
        run: |
          echo "Performance tests disabled"

  # =========================================================
  # DEPLOY REPORTS
  # =========================================================

  deploy-reports:

    needs:
      - performance-tests

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # =====================================================
      # Karate Reports
      # =====================================================

      - name: Download Karate Reports
        uses: actions/download-artifact@v4
        with:
          name: karate-reports
          path: site/${{ github.event.inputs.suite_name }}/latest/karate

      # =====================================================
      # Gatling Reports
      # =====================================================

      - name: Download Gatling Reports
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_performance == 'true'
        uses: actions/download-artifact@v4
        with:
          name: gatling-report
          path: site/gatling

      # =====================================================
      # Upload Pages Artifact
      # =====================================================
      - name: Copy QA Portal
        run: |
          cp portal/index.html site/index.html

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      # =====================================================
      # Deploy
      # =====================================================

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4