name: FWKarate2xx CI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  functional-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run functional tests
        run: ./gradlew apiTest -Ptags=@smokes

      - name: Upload Karate Reports
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: build/karate-reports

  performance-tests:

    needs: functional-tests

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run performance tests
        run: ./gradlew performanceTest -Ptags=@perf

      - name: Prepare Gatling Site
        run: |
            mkdir -p build/gatling-site
            latest=$(ls -td build/reports/gatling/* | head -1)
            cp -r "$latest"/* build/gatling-site/

      - name: Upload Gatling Reports
        uses: actions/upload-artifact@v4
        with:
            name: gatling-report
            path: build/gatling-site

  deploy-reports:

    needs:
      - performance-tests

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # Karate
      - name: Download Karate Reports
        uses: actions/download-artifact@v4
        with:
          name: karate-reports
          path: site/karate

      # Gatling
      - name: Download Gatling Reports
        uses: actions/download-artifact@v4
        with:
          name: gatling-report
          path: site/gatling

      # Upload unified site
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      # Deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4